# Floating Point Numbers

The number of bits is usually fixed for any given computer. Using binary representation gives us an insufficient range and precision of numbers to do relevant engineering calculations. To achieve the range of values needed with the same number of bits, we use floating point numbers or float for short. Instead of utilizing each bit as the coefficient of a power of 2, floats allocate bits to three different parts: the sign indicator, s
, which says whether a number is positive or negative

In [37]:
import sys
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [38]:
import numpy as np


In [39]:
np.spacing(1e9)

1.1920928955078125e-07

Use the spacing function to determine the gap at 1e9. Verify that adding a number to 1e9 that is less than half the gap at 1e9 results in the same number.

In [40]:
1e9 == (1e9 + np.spacing(1e9)/4)

True

# Write a file

f = open(filename, mode)

f is the returned file object. The filename is a string where the location of the file you want to open, and the mode is another string containing a few characters describing the way in which the file will be used, the common modes are:

‘r’, this is the default mode, which opens a file for reading

‘w’, this mode opens a file for writing, if the file does not exist, it creates a new file.

‘a’, open a file in append mode, append data to end of file. If the file does not exist, it creates a new file.

‘b’, open a file in binary mode.

‘r+’, open a file (do not create) for reading and writing.

‘w+’, open or create a file for writing and reading, discard existing contents.

‘a+’, open or create file for reading and writing, and append data to end of file.



In [41]:
f = open('test.txt','w')

for i in range(6):
  f.write(f" this is line {i}\n")

f.close()

## Append to a file

In [42]:
f = open('test.txt','a')
f.write(f"this is another line to check the append \n")

f.close()


## reading a file

In [43]:
f = open('./test.txt','r')

content = f.read()
f.close()

print(content)

 this is line 0
 this is line 1
 this is line 2
 this is line 3
 this is line 4
 this is line 5
this is another line to check the append 



In [44]:
type(content)

str

# Dealing with numbers and arrays

 Store an array [[1.20, 2.20, 3.00], [4.14, 5.65, 6.42]] to a file named my_array.txt and read it back to a variable called my_arr.

In [45]:
arr = np.array([[1.20, 2.20, 3.00], [4.14, 5.65, 6.42]])
arr

array([[1.2 , 2.2 , 3.  ],
       [4.14, 5.65, 6.42]])

## saving the output

In [46]:
np.savetxt('my_arr.txt', arr, fmt='%2f', header = 'col1 col2 col3')

We can see from the above example to save a 2D array into a text file using np.savetxt. The first argument is the file name, second argument is the arr object we wave to save, and the third argument is to define the format for the output (I use ‘%.2f’ to indicate we want the output numbers with 2 decimals). The fourth argument is the header we want to write into the file.

In [47]:
my_arr = np.loadtxt('my_arr.txt')
my_arr

array([[1.2 , 2.2 , 3.  ],
       [4.14, 5.65, 6.42]])

# Write and open a CSV file

In [48]:
data = np.random.random((100,5))

In [49]:
np.savetxt('test.csv', data, fmt = '%.2f', delimiter=',', header='c1,c2,c3,c4,c5')

We first generate the random data for 100 rows and 5 columns using the np.random function and assign it to data variable. We use the np.savetxt function to save the data to a csv file. We can see that the first 3 arguments are the same for the ones used in the previous section, but here we set the delimiter argument to ‘,’, which indicate that we want to separate the data using comma.

# Read a CSV file

In [50]:
my_csv = np.loadtxt('./test.csv', delimiter=',')
my_csv[:5, :]

array([[0.9 , 0.38, 0.92, 0.12, 0.31],
       [0.21, 0.54, 0.29, 0.44, 0.96],
       [0.27, 0.05, 0.23, 0.65, 0.7 ],
       [0.62, 0.74, 0.54, 0.42, 0.29],
       [0.32, 0.12, 0.98, 0.47, 0.34]])

As before, we could read in the csv file using the np.loadtxt function. Let’s read in the csv file we just saved to the disk to a variable my_csv, and output the first 5 rows. Note here we use the delimiter again to specify that the data in the file is separated by commas

In [51]:
my_csv[:, :]

array([[0.9 , 0.38, 0.92, 0.12, 0.31],
       [0.21, 0.54, 0.29, 0.44, 0.96],
       [0.27, 0.05, 0.23, 0.65, 0.7 ],
       [0.62, 0.74, 0.54, 0.42, 0.29],
       [0.32, 0.12, 0.98, 0.47, 0.34],
       [0.63, 0.86, 0.5 , 0.13, 0.06],
       [0.78, 0.71, 0.83, 0.49, 0.69],
       [0.88, 0.29, 0.83, 0.3 , 0.08],
       [0.43, 0.94, 0.97, 0.21, 0.  ],
       [0.01, 0.22, 0.16, 0.6 , 0.32],
       [0.96, 0.22, 0.59, 0.88, 0.66],
       [0.06, 0.89, 0.13, 0.98, 0.16],
       [0.3 , 0.85, 0.06, 0.09, 0.51],
       [0.23, 0.19, 0.08, 0.29, 0.71],
       [0.28, 0.09, 0.66, 0.18, 0.85],
       [0.63, 0.45, 0.59, 0.67, 0.25],
       [0.87, 0.6 , 0.  , 0.22, 0.7 ],
       [0.61, 0.44, 0.71, 0.44, 0.86],
       [0.13, 0.21, 0.26, 0.5 , 0.81],
       [0.18, 0.44, 0.49, 0.65, 0.86],
       [0.23, 0.63, 0.86, 0.04, 0.84],
       [0.82, 0.54, 0.31, 0.25, 0.84],
       [0.45, 0.83, 0.21, 0.4 , 0.15],
       [0.97, 0.6 , 0.57, 0.85, 0.07],
       [0.03, 0.13, 0.62, 0.82, 0.81],
       [0.62, 0.54, 0.93,

#Pickle Files

introduce another way to store the data to the disk - pickle. We talked about saving data into text file or csv file. But in certain cases, we want to store dictionaries, tuples, lists, or any other data type to the disk and use them later or send them to some colleagues. This is where pickle comes in, it can serialize objects so that they can be saved into a file and loaded again later.

Pickle can be used to serialize Python object structures, which refers to the process of converting an object in the memory to a byte stream that can be stored as a binary file on disk. When we load it back to a Python program, this binary file can be de-serialized back to a Python object.



# Write a pickle file

Create a dictionary, and save it to a pickle file on disk. To use a pickle, we need to import the module first.

In [52]:
import pickle

In [53]:
dict_a = {'A' : 0, 'B':1, 'C':2}
pickle.dump(dict_a, open('text.pkl', 'wb'))

To use pickle to serialize an object, we use the pickle.dump function, which takes two arguments: the first one is the object, and the second argument is a file object returned by the open function. Note here the mode of the open function is ‘wb’ which indicates write binary file.



# Read a pickle file

In [54]:
my_dict = pickle.load(open('./text.pkl', 'rb'))
my_dict

{'A': 0, 'B': 1, 'C': 2}

We can see the loading of a pickle file is very similar to the saving process, but here the mode of the open function is ‘rb’ indicates read the binary file. And this function will be de-serialize the binary file back to the original object, which is a dictionary in our case.



# JSON Files

JSON is another format we are going to introduce. It stands for JavaScript Object Notation. A JSON file usually ends with extension “.json”. Unlike pickle, which is Python dependent, JSON is a language-independent data format, which makes it attractive to use. Besides, it is usually takes less space on the disk and the manipulation is faster than pickle (if you are interested, search online to find more materials about it). Therefore, it is a good option to store your data using JSON. In this section, we will briefly explore how to handle JSON files in Python.



## JSON format

The text in JSON is done through quoted string containing value in key-value pairs within {}. It is actually very similar to the dictionary we saw in Python. For example:

In [55]:
{
  "school": "UC Berkeley",
  "address": {
    "city": "Berkeley",
    "state": "California",
    "postal": "94720"
  },

  "list":[
      "student 1",
      "student 2",
      "student 3"
      ]
}

{'school': 'UC Berkeley',
 'address': {'city': 'Berkeley', 'state': 'California', 'postal': '94720'},
 'list': ['student 1', 'student 2', 'student 3']}

# Write a JSON file

In [56]:
import json

In [57]:
school = {
  "school": "UC Berkeley",
  "address": {
    "city": "Berkeley",
    "state": "California",
    "postal": "94720"
  },

  "list":[
      "student 1",
      "student 2",
      "student 3"
      ],

  "array":[1, 2, 3]
}
json.dump(school, open('school.json', 'w'))

To use json to serialize an object, we use the json.dump function, which takes two arguments: the first one is the object, and the second argument is a file object returned by the open function. Note here the mode of the open function is ‘w’ which indicates write file.



# Read a JSON file

In [58]:
my_school = json.load(open('./school.json', 'r'))
my_school

{'school': 'UC Berkeley',
 'address': {'city': 'Berkeley', 'state': 'California', 'postal': '94720'},
 'list': ['student 1', 'student 2', 'student 3'],
 'array': [1, 2, 3]}